// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN4bR3ZwL_ajif6D1bV1lkvR7PICFrTYA',
    appId: '1:984412147983:android:6d16874ac08ee157e3ae7a',
    messagingSenderId: '984412147983',
    projectId: 'bookcrossingapp-98fa3',
    storageBucket: 'bookcrossingapp-98fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5aNqC7doQVTv1DTtsTuAfdy6dtFVaVk',
    appId: '1:984412147983:ios:6f09d125d846596ce3ae7a',
    messagingSenderId: '984412147983',
    projectId: 'bookcrossingapp-98fa3',
    storageBucket: 'bookcrossingapp-98fa3.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookcrossingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5aNqC7doQVTv1DTtsTuAfdy6dtFVaVk',
    appId: '1:984412147983:ios:6f09d125d846596ce3ae7a',
    messagingSenderId: '984412147983',
    projectId: 'bookcrossingapp-98fa3',
    storageBucket: 'bookcrossingapp-98fa3.firebasestorage.app',
    iosBundleId: 'com.example.flutterBookcrossingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCakTjULUoQ5NxCTRGYRKHO6C5v5TCLBds',
    appId: '1:984412147983:web:9b555dc742fef04be3ae7a',
    messagingSenderId: '984412147983',
    projectId: 'bookcrossingapp-98fa3',
    authDomain: 'bookcrossingapp-98fa3.firebaseapp.com',
    storageBucket: 'bookcrossingapp-98fa3.firebasestorage.app',
    measurementId: 'G-6T1SP8ED4C',
  );

}